apiVersion: apps/v1
kind: Deployment
metadata:
  name: noracle-service
  namespace: ma-breuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noracle-service
    spec:
      volumes:
        - name: las2peer-nodestorage-persistent
          persistentVolumeClaim:
            claimName: noracle-pvc
        - name: registry-config-volume
          configMap:
            name: registry-config
            defaultMode: 420
      containers:
        - name: noracle-service
          image: >-
            registry.tech4comp.dbis.rwth-aachen.de/rwthacis/noracle-service:1.0.0
          env:
            - name: BOOTSTRAP
              value: las2peer-bootstrap.sbf-dev:32011
            - name: NODE_ID_SEED
              value: '382251'
            - name: LAS2PEER_PORT
              value: '32061'
          volumeMounts:
            - name: las2peer-nodestorage-persistent
              mountPath: /src/node-storage
            - name: registry-config-volume
              mountPath: >-
                /src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties
              subPath: registry-config.properties
